src/2d/shallow/filval.f90
Remove test in src/2d/shallow/filval.f90 that xl==xl2 and yb==yb2 -- originally for debugging in @ca673af7d and uses absolute error in way that can fail, as discovered by a user,
https://groups.google.com/forum/?fromgroups#!topic/claw-users/NO0m1UAczw4
=> Remove test in src/2d/shallow/filval.f90 that xl==xl2 and yb==yb2 

src/python/geoclaw/dtopotools.py
If `input_units` were not being specified to the `Fault` class the updated
dictionary was not being used (the input, which was `None`, was being used
instead).
=> Fix `input_units` bug

.travis.yml
This cleans up the error handling in the travis script so that if the tests fail that the logs are dumped.
=> Fix travis failure output of tests

src/2d/shallow/stepgrid.f
This fixes an uninitialized variable problem that almost never became an issue although in principle could have.  It will stop execution if the compiler was instructed to watch for uninitialized variables.  I think that setting `tcfmax = -rinfinity` should work but if there is a more sensible setting then let me know.
=> Initialize `tcfmax` to `-rinfinity`

src/2d/shallow/test_parse_values.f90, src/2d/shallow/topo_module.f90, src/2d/shallow/utility_module.f90, src/python/geoclaw/topotools.py, tests/test_topotools.py
Replaces #134.
Allows dx and dy on the same line for topotype 2,3 rather than introducing new topotypes. 
Also allows values or labels to come first, so `topotools.swapheader` does not need to be applied to data from NGDC.  Not yet fully tested.
The new subroutine `parse_values` in `utility_module.f90` might be useful more generally.  Contains ugly string manipulation in Fortran -- maybe someone knows a better way to write this...
@mandli: I haven't yet rewritten the Python tools yet to support this.  Is it ok to change `Topography.delta` to always be a tuple `(dx,dy)` as in #134?
=> [WIP] Topotypes 2 and 3 - parse values to allow dx and dy on cellsize line

tests/dtopo1/Makefile, tests/storm_surge/Makefile
=> fix Makefiles in tests that pointed to wrong amr2.f90

src/2d/shallow/surge/storm_module.f90
This caused some compilers to complain at compile time without these attributes.
=> Add `save` attribute to storm types

src/2d/shallow/fgmax_interpolate.f90, src/2d/shallow/fgmax_interpolate0.f90, src/2d/shallow/tick.f
Minor changes to remove tabs from source (gcc 5.x have changed these from warnings to errors by default).
=> Convert all non-conforming tabs to spaces

.travis.yml
Only run if tests failed but was failing itself because of a syntax error.  Addresses #169.
=> Remove extraneous `fi` from travis script

src/python/geoclaw/topotools.py
In trying to update the notebook
http://nbviewer.ipython.org/url/clawpack.github.io/notebooks/topotools_examples.ipynb
I ran into this bug.
But after fixing, it gives a funny result.  The last figure looks wrong
@mandli: can you investigate?
=> topotools unstructured bugs

src/python/geoclaw/topotools.py
Now a custom Normalize object is used to map from data to the colormap
to handle uneven topo limits when necessary (otherwise just uses the
standard linear mapping).
See clawpack/visclaw#118 for the original issue and clawpack/visclaw#169 for the solution.
=> Adapt `topotools.Topography.plot` to new `add_colorbar`

src/2d/shallow/fgmax_frompatch_arrival_velocity.f90
Added `src/2d/shallow/fgmax_frompatch_arrival_velocity.f90`
This can be used instead of the default `fgmax_frompatch.f90` to flag arrival times based on amplitude of velocity rather than on surface elevation.    Flags arrival if `abs(sqrt(u**2 + v**2)) > arrival_tol` and detects first motion of water, including outflow, important in a harbor, for example.
Works better particularly in regions of subsidence, where the default routine doesn't flag arrival until surface elevation is above original sealevel + `arrival_tol`
Will be used only if user changes Makefile to point to this routine.
=>  Flag arrival times based on velocity option

src/python/geoclaw/etopotools.py, tests/etopo1/fetch_etopo.py, tests/etopo1/test_etopo.py
This could eventually be put in topotools, but we might want to improve further first.
In particular I haven't yet figured out how to specify grid registered vs. cell registered data in the URL.
See http://www.ngdc.noaa.gov/mgg/global/global.html
There is a nosetest and also a sample script in `tests/etopo1`.
=> Etopotools

examples/tsunami/chile2010/maketopo.py
A few syntax/path corrections when saving png images.
=> Bug fixes in maketopo.py of geoclaw/examples/tsunami/chile2010

src/2d/shallow/gfixup.f, src/python/geoclaw/dtopotools.py
This bug never showed up since time isn't used, but I'm working on a time-dependent variable sea level option that uncovered it.
I don't know that time really needs to be a private variable in this loop, but this was easiest way to fix.
=> Set omp private variable time in gfixup.f

src/2d/shallow/amr2.f90
A commit that added some new timing information added tabs to `tick.f`.  This removes them.
=> Remove Non-Conforming Tabs

src/2d/shallow/amr2.f90, src/2d/shallow/tick.f
I think this fixes the problem, but there might be something else I missed.  I haven't tested much yet.
=> fixes to make checkpt_style < 0 work in geoclaw

src/python/geoclaw/fgmax_tools.py
Add fgmax_tools.adjust_fgmax_grid utility to adjust limits of a desired fgmax grid so it's aligned with the finest computational grid.
This avoids interpolation when monitoring values on the fgmax grid and will just use the cell-centered values from the computation.  Avoids problems near the coast in particular when interpolating surface since otherwise surface values onshore may contaminate surface elevations being monitored.
=> adjust_fgmax

src/python/geoclaw/topotools.py
add option to Topography.write to write header with ARCGIS order of label then value.
To make it possible to output newly created topo file in a way that can be read into ARCGIS.
=> Topography header order

src/2d/shallow/topo_module.f90
in `read_topo_file` function, line containing `no_data_value` was truncated if more than 20 characters, causing wrong value to be used (e.g. -99 instead of -99999, meaning any topo at -99 was reset arbitrarily to -150).  
If this happens, a warning message reporting missing data stated "see fort.missing", which was itself missing.  Removed this and instead point to the subroutine.  Add print statements the user can uncomment to see where the missing data is.
=> Topo module str length

src/2d/shallow/qad.f
not used in qad but passed in to rpn2 and could cause problems there.
=> waves and s declared with wrong dimensions in qad 

src/python/geoclaw/topotools.py
needs keywords xllcorner,yllcorner instead.
=> arcgis/qgis does not read header properly with xlower,ylower 

src/2d/shallow/fgmax_interpolate0.f90
Was computing index incorrectly for cell that fgmax point lies inside. It was sometimes correct and sometimes off by 1 depending on rounding.
Now should be correct, but note that if fgmax point lies right on cell edge then might use cell to left or cell to right depending on rounding. I don't see a way to make this more deterministic.
=> Fgmax interpolate0 index

src/2d/shallow/gauges_module.f90
But it is commented out and only to be used when debugging.
=> improve gauge interpolation test

src/python/geoclaw/dtopotools.py
=> dtopotools.DTopography should not require dx == dy

src/python/geoclaw/dtopotools.py, tests/old_dtopotools.py, tests/storm_surge/regression_tests.py
Remove tabs, specify binary file format, and use '==' instead of 'is'.
=> Additional fixes for compatibility with Python3

src/2d/shallow/Makefile.geoclaw, tests/bowl_slosh/Makefile
As suggested in documentation,
http://www.clawpack.org/fgmax.html
(which needs to be updated for 5.4.0 Makefile).
=> change Makefile.geoclaw to use fgmax_interpolate0.f90

src/2d/shallow/gauges_module.f90
Needed for precise positioning of longitude,latitude in geoclaw.
Previous format could be off by 5 meters.  Change from 7 to 10 digits, which may
be overkill, but agrees with number of digits printed in gauges.data file
used as input.
=> print more digits in gauge locations

src/2d/shallow/fgmax_interpolate0.f90, src/python/geoclaw/dtopotools.py, src/python/geoclaw/topotools.py
After checking again, I think `fgmax_interpolate0.f90` is correct and I have removed the warning message that raised concerns in https://groups.google.com/forum/#!topic/claw-users/r_eeWVx6tgw
=> remove unnecessary warning message

src/2d/shallow/gauges_module.f90
Setting to .false. will suppress bilinear interpolation and always use value from cell containing gauge.  It is set to .true. so this shouldn't change the behavior from the previous version.  
Note that the interpolating version uses bilinear interp if all surrounding cells are wet, but takes the cell value if at least one is dry. 
This modification is similar to the `fgmax_interpolate0.f90` routine that takes the cell value rather than interpolating.  
Eventually we might want to add options to setrun.py to select whether to interpolate or not for both of these routines.
=> add INTERPOLATE parameter to gauges_module.f90

src/2d/shallow/gauges_module.f90, src/2d/shallow/multilayer/gauges_module.f90
This is just a minor tweak that causes and error from `setbestsrc` to output the gauge number rather than the index of the gauge which is not so helpful.
=> Output gauge number rather than index

examples/storm-surge/ike/setplot.py, src/python/geoclaw/multilayer/plot.py, src/python/geoclaw/surge/plot.py
In some instances the land bounds were not being set making the land plotting janky (technical term for awful).
=> Add back default land bounds

src/python/geoclaw/dtopotools.py, tests/test_dtopotools.py
The value of rigidity (mu) was not being set for SIFT faults.  Set it properly so Mw agrees with PMEL's version.
=> Sift fault mu value

src/2d/shallow/amr2.f90
To fix deletion of these variables and print statements.  
Should now agree with amrclaw version again, and print out total time statistics at the end of a run.
The write statements were commented out in 5bdb1e2.  Not clear where the declaration of the variables got dropped, but it wasn't working at that time because of lack of proper `use` statements.
=> add timeTick and timeTickCPU back into amr2.f90 

src/2d/shallow/Makefile.geoclaw
`flagregions2.f90` is also in `Makefile.geoclaw` and is the one actually used.  `flagregions` is a left-over.
Bigger question to discuss: where should we flag regions in geoclaw, see #298.
=> flagregions.f90 never used, remove from Makefile.geoclaw

src/2d/shallow/topo_module.f90
Sets `topo0save` in a different place to deal with the situation where a topo file overlaps a dtopo file and hence should be updated by the dtopo, but no dtopo grid point lies in the extent of the topo file.
We ran into a problem with a topo file that only covered a few square meters on shore (specifying a potential tsunami vertical evacuation berm at sub-meter resolution) while the dtopo file had grid points much farther apart and so no dtopo point lies within the extent of the topo file.  With the old code, this topo file was not properly adjusted for the subsidence that occurs onshore from a nearby earthquake, and hence the berm did not properly subside along with the surrounding topography.
=> set topo0save for all topo grids overlapped by dtopo grids

src/python/geoclaw/etopotools.py
The etopo1 file downloaded will in general have different `xllcorner, yllcorner` than the values requested by the user in `xlimits, ylimits` and the topofile written out should have the values downloaded, not those requested.
*Note:*
- It was recently noticed that this does not always download the right thing if a resolution is requested that is coarser than 1 arcminute, as illustrated in [this notebook](http://depts.washington.edu/ptha/etopo_registration_tests.html)  
- This seems to be a problem with the NCEI server, but they are no longer supporting this approach so any bugs probably won't be fixed.  I added a warning message if the user requests something other than `dx=dy=1/60.`
- There is now a much better way to do download etopo1 data, by opening a remote NetCDF file and …
=> etopotools -- corners from file

src/2d/shallow/topo_module.f90, src/python/geoclaw/dtopotools.py, src/python/geoclaw/kmltools.py, src/python/geoclaw/topotools.py
This is to deal with the issue that we always interpreted DEM files incorrectly if the header specifies `xllcorner, yllcorner`, see #276 and https://groups.google.com/forum/#!topic/claw-users/a0sK7dwETvE
This changes how the data is interpreted when DEMs of this form are read in to either the Fortran code (changes to `topo_module.f90`) or into Python using `topotools.py`, and therefore will change the computed results in these cases.
I am working on some documentation that explains all this better, comments welcome on the drafts at
- http://depts.washington.edu/clawpack/sampledocs/v5.5.0alpha/topo.html
- http://depts.washington.edu/clawpack/sampledocs/v5.5.0alpha/grid_registration.html
It would be good if someone experiments with this before we merge it.
Note: the chile2010 example uses a …
=> Grid registration - handle xllcorner,yllcorner properly

src/2d/shallow/tick.f
It is now declared in amrclaw/src/2d/amr_module.f90
Addresses #316.
=> remove tick_clock_start declaration from tick.f

src/python/geoclaw/dtopotools.py
@rjleveque Thanks for the comments from [github.com/rjleveque/geoclaw/pull/3](https://github.com/rjleveque/geoclaw/pull/3). I've made some fixes in this PR.
[1-3] I think I mistakenly did a double-negative. I defined a logical ``self._fix_orientation``: when it switches on (the orientation is clock-wise), I multiply a negative sign to fix the sign error. I agree that the data user input should be preserved, probably can confuse the user.
[4-5] I removed the optional ``rake=90.`` argument to ``self.calculate_geometry_triangles()`` and also made the ``rake`` input required for ``self.set_corners()``, as suggested. (I think in the past I looked through all the triangular subfaults in CSZ and seeing them all having rake of 90 degrees I assumed that 90 degrees was the default for most cases.) …
=> Fixed orientation issue / rake is required to be set in set_corners()

examples/tsunami/chile2010/README.rst, examples/tsunami/chile2010/setplot.py, examples/tsunami/chile2010/setrun.py, src/python/geoclaw/kmltools.py
This increases the number of digits put into kml files showing gauges, and extent of topo, dtopo, regions, both in the number used to position and in the text box descriptions (using a function `f2s` that converts floats to strings with trailing zeros removed but with more digits than the `%g` format - maybe there's a better way to do this?). 
I modified the chile2010 example to make these kml files by default since this is generally very useful to make sure things are placed where expected.  I added some description to the `README.rst`.
In testing this, I also tried 
```
make plots SETPLOT_FILE=setplot_kml.py
```
and discovered that it seems to still make the png files properly (by unzipping Chile2010.kmz) and opening one) but when the kmz file is opened in my current version of Google …
=> kmltools -- increase number of digits printed

src/2d/shallow/multilayer/update.f90, src/2d/shallow/update.f90
I would like to raise a discussion on this single line of code in update.f90.
I think here we should compare **q(1,i,j)** instead of **hf = q(1,i,j) * capa** to **dry_tolerance** in update.f90. 
One simple argument is that at all other places, **q(1,i,j)**  instead of **q(1,i,j) * capa** is compared to **dry_tolerance**.
Any thought?
=> compare q(1,i,j) instead of q(1,i,j)*capa to dry_tolerance in update.f90

src/python/geoclaw/topotools.py
simplify slicing notation in this case.
@mandli: I think you said at one time that you were having trouble downloading some netcdf topo for  a storm surge problem.  Maybe you can check if this fixes your problem (and/or still works).
=> topotools.read_netcdf sometimes failed with coarsen==1

src/python/geoclaw/surge/plot.py
Summary
-------
- Define `surge_data` which was previously being used without being defined
- Make land plots compatible with other `pcolor` plots by not fixing bounds by default; otherwise, the land plot interferes with the scale
- Add name for bathy plotitem
Testing
-------
- Manually tested by making plots for Katrina model
=> Minor plotting fixes

.travis.yml
Note that this was not reproducible on local setups and only
seemed to be happening with travis.
=> Require xarray version 0.11.0 so that travis tests do not fail

.travis.yml, tests/old_topotools.py
- pull latest xarray version on travis  now that latest is `>=0.12` and the bug we had with `0.11.3` no longer requires us to pin `xarray==0.11.0` (see #362 and #354)
- install `scipy` on travis so that no tests requiring `scipy` are skipped
- remove unneeded import of `pylab` package that causes `test_topotools.test_against_old()` to be skipped if `pylab` not installed. `pylab` is no longer needed for that test anyway.
=> Update package dependencies for travis and tests

src/python/geoclaw/surge/storm.py
Some ATCF data files for old storms don't have central pressure. Right now, this will throw an error trying to read and convert an empty string. This PR fixes that and assigns a -1 missing value. It also updates `write_geoclaw` such that it won't print a line with a -1 value for `max_wind_speed` or `central_pressure`. We could treat these similarly to the radius parameters and allow for a "fill function" but for now I think it's fine to just drop these rows?
=> handle missing ATCF pressure

tests/chile2010_adjoint/Makefile, tests/chile2010_adjoint/adjoint/Makefile
This makes the test fail if run in a non-git version of the code,
e.g. obtained from a tar file.  
We should improve clawutil.claw_git_status.py
to not throw an error in this case eventually.
https://github.com/clawpack/clawutil/issues/135
=> remove GIT_STATUS from test Makefiles

examples/tsunami/bowl-radial/setplot.py
Plotting all gauges was putting gauges way outside the zoom region and adjusting the figure size to include them all when doing `make plots` though not interactively.  Not sure what changed in visclaw or matplotlib to make this happen, but now fixed for this example at least.
I raised an issue to investigate further:
https://github.com/clawpack/visclaw/issues/243
=> fix examples/tsunami/bowl-radial zoom plots

src/python/geoclaw/dtopotools.py, src/python/geoclaw/topotools.py
the kwarg is `style` not `format`, and matplotlib 3.1.1 throws an error
while older versions just ignored it.  Could omit this kwarg altogether.
=> fix ticklabel_format kwarg

src/2d/shallow/fgmax_read.f90
Need to inquire if the file exists before opening it.
There was an extra un-needed open statement in the wrong place.
=> fix fgmax_read.f90 check for missing file

src/2d/shallow/topo_module.f90, tests/netcdf_topo/regression_tests.py
This is useful particularly for the use case where you have a global DEM that you want to repeatedly use as the lowest-resolution "base" topography for multiple storm runs, but you don't want to read in the entire world of topography if each domain is much smaller.
=> Only read part of netCDF inside domain

src/python/geoclaw/surge/storm.py
In our use cases, we found a need to not throw an error if you feed it a storm that actually has no observed max wind or central pressure values, but to instead return a `Storm` object with no time points. I figure this is a consistent behavior so maybe worth merging into master. But if you think it's better to throw a ValueError in these situations, I'm happy to keep this change on `ClimateImpactlab/geoclaw` and not merge.
=> handle missing storms in read_ibtracs

src/2d/shallow/advanc.f
This one line seems to have two bugs in it, can you take a look @mjberger or @mandli?
The corresponding line in `amrclaw/src/2d/advanc.f` also seems to have one of the bugs.  There it has
```
call update_gauges(alloc(locnew:locnew+nvar*mitot*mjtot),
.                       alloc(locaux:locaux+nvar*mitot*mjtot),
.                       xlow,ylow,nvar,mitot,mjtot,naux,mptr)
```
and I think `nvar` should be `naux` on the second line?  Also the same problem in `1d` and `3d` amrclaw.
I came across this when reviewing #358 since I'd like to update that and try it out, and noticed there was a commit that partly fixed this line and then it was reverted in the second commit.  Not sure why but maybe @xinshengqin can comment.
=> bug in call to update_gauges?

src/2d/shallow/topo_module.f90, src/python/geoclaw/data.py
Missing data values in topofiles were set to -150, which was arbitrary and not a good value to use, see #327 
Now set to 99999. by default and this value can be set in `setrun.py`. If there are missing values and this default is being used then the code halts with an error like:
```
WARNING...      6 missing data values in this topofile
These values have been set to topo_missing =     99999.000 in read_topo_file
ERROR... do not use this default value
Fix your topofile or set
rundata.topo_data.topo_missing in setrun.py
```
This value is written to `topo.data` and expected by the Fortran code, so users need to remake data and `make new` to incorporate the changes.
=> Topo missing

examples/multi-layer/bowl-radial/setrun.py
Minor bug fix to reduce number of aux fields required for multilayer bowl-radial example.
=> Specify correct number of aux fields

examples/tsunami/chile2010/setplot.py, src/2d/shallow/advanc.f, src/2d/shallow/amr2.f90, src/2d/shallow/gfixup.f, src/2d/shallow/tick.f, src/2d/shallow/valout.f90
See https://github.com/clawpack/amrclaw/pull/250 for discussion of the changes in this PR.
The `chile2010` example also has a modified `setrun.py` to plot timing stats, using https://github.com/clawpack/visclaw/pull/247
=> improving timing with 8 byte integers

examples/tsunami/bowl-slosh-netcdf/setplot.py, examples/tsunami/bowl-slosh/setplot.py, tests/bowl_slosh/setplot.py, tests/dtopo1/setplot.py
Since `matplotlib.find` is deprecated, use `where` instead in some `setplot.py` files.
Also a missing `ravel` in a couple files for plotting the bowl-slosh surface.
=> Use where instead of find in some places

.gitignore, .travis.yml, tests/netcdf_topo/regression_tests.py
We were having some issues with netcdf in our build of clawpack and I realized that we have actually never been testing netcdf on travis. Previously, the netcdf tests would pass if netcdf-based builds failed. At some point, I changed this behavior to "Skip" but since that point, all travis builds have skipped. I installed the appropriate netcdf libraries and now that test is passing "for real".
I also bumped the python 3.x version to 3.7. We could test on 3.5 (and any other 3.x) as well if you think its useful?
Finally, I just added the macOS .DS_Store file to the gitignore since it was annoying me.
=> make netcdf build on travis

examples/tsunami/chile2010/setrun.py, src/2d/shallow/amr2.f90, src/2d/shallow/qad.f, src/2d/shallow/stepgrid.f
Required to go with clawpack/amrclaw#253.
max1d is now a parameter that can optionally be set in setrun.py as `rundata.amrdata.max1d`. Otherwise it has the default value 60 from 2d amrclaw.  Shows up in `amr.data`.
Hoping this passes travis tests since https://github.com/clawpack/clawpack/pull/170 has been merged.
=> Variable max1d

src/python/geoclaw/topotools.py
This is needed by `kmltools.topo2kml` when making a kml file showing the extent of a topo file specified with `topo_type==4` (netCDF files).
=> extend Topography.read_header function handle netCDF files

src/python/geoclaw/surge/storm.py
The utility function `fill_rad_w_other_source` fills in missing wind radius data, amongst others, using interpolation. This PR makes sure that no NaNs are present in the interpolation step. Furthermore, it adds an optional parameter (`interp_kwargs`) to `fill_rad_w_other_source` that is passed on to xarray's `DataArray.interp(...)` where it is used as keyword arguments to scipy's interpolator. A typical use case would be to specify `{ 'fill_value': 'extrapolate' }`.
=> Interpolation in fill_rad_w_other_source

src/python/geoclaw/topotools.py
With some versions of numpy, it won't accept a float64 dtype as the `num` kwarg for `np.linspace`. I noticed this b/c it failed the build of our ClimateImpactLab/clawpack fork when we merged in the latest changes to clawpack/clawpack
=> Fix annoying numpy issue

src/2d/shallow/amr2.f90, src/2d/shallow/multilayer/gauges_module.f90, tests/multilayer/Makefile
Lagrangian gauges aren't yet handled in multilayer code but some variables need to be added to the `gauge_type`. 
There aren't used unless doing a restart, but the latest gfortran caught this and `tests/multilayer` didn't pass.
I also decided to check that restarting works and it didn't because of another issue: In `amr2.f90` it is now necessary to call `set_geo` and `set_multilayer` before `set_gauges` so the number of layers is set.
At some point, need to investigate whether other `set_*` routines should best be called before or after `restrt`, depending on whether the user should be allowed to modify various things in the restart from the original run.
But I think things are working again as in v5.6.1.
=> Multilayer gauge fix

examples/tsunami/eta_init_force_dry/setplot.py
Left over from an earlier test version before things were merged into geoclaw.
=> remove unneeded addition to python path in a setplot

src/python/geoclaw/kmltools.py
Make sure that vmin,max are labeled to make it clear where the
colorscale ends, particularly useful when other points are masked out
=> improve ticks on kml colorbars

src/python/geoclaw/topotools.py
Some netCDF files use `x` and `y` as the horizontal variables rather than `lon`, `lat`, so check for this case instead of failing.
We could add `xvar` and `yvar` input parameters similar to `zvar`, but that would mean a new call signature and probably there aren't other variable names being used.
It now also prints out `f.variables` if it doesn't find one of the expected names.
=> in read_netcdf, allow variables x,y in place of lon,lat

src/2d/shallow/multilayer/setaux.f90, src/2d/shallow/setaux.f90, src/2d/shallow/topo_module.f90
The main fix in this PR is to make the `var_ids` vector in the `netcdf_module` allocatable. Previously, it had been a static array of length 2, but all netcdf topo files will have at least 3 vars (x, y, z), which was the length of the array that was returned from the `nf90_inq_varids` call. So I'm not sure how this was working for so long. I switched to an allocatable array, which gets allocated after reading the number of variables in the file in an earlier call. Somehow, this memory issue had not been causing segfaults unless I had the `fstack-protector` flag on, in which case it caused a segfault. But even when it was not segfaulting, it was giving wacky behavior for runs with netcdf topo. In particular, it was giving different results depending on whether you redirected stdout and …
=> fix memory and cleanup netcdf mod

src/2d/shallow/surge/model_storm_module.f90
The main change from this PR is to close #465 by clipping azimuthal wind speed at 0 (no negative values). In addition, I cleaned up the model_storm_module file a bit by pulling out common pre- and post-processing functionality into separate subroutines (including this bounding at 0 function). I noticed a few errors in some of the wind models that I noted in #466 but didn't address as my knowledge of these wind models is limited
=> Clean up model_storm_module and bound azimuthal wind at 0

src/python/geoclaw/util.py, tests/test_util.py
Previously, this method would expect different formatting from the NOAA API, leading to a Value Error being thrown.
=> Fix fetch_noaa_tide_data() method to match current NOAA API formatting

src/python/geoclaw/topotools.py
In case y is in decreasing order, flip so it is increasing, and also flip Z.
Recall that topofiles list values from north to south, so y decreases, but in
Topography object y increases.
Also print more info if exception occurs.
=> flip Y if needed in Topography.set_xyZ

tests/test_etopo1.py
The NOAA thredds server is sometimes down, making travis fail. 
This would issue a warning instead. 
@mandli: Look ok to do it this way?
=> warn instead of fail if etopo1 data can't be read from thredds server

src/2d/shallow/filval.f90, tests/test_etopo1.py
This PR fixes #476 . It also makes the try/except clause in the etopo test a bit more precise (i.e. it only allows OSError or RuntimeError exceptions) just to avoid skipping errors that aren't due to the THREDDS server.
=> Fix call to preinterpcopy; specify exceptions in test_etopo1

src/2d/shallow/restrt.f
If a restart is done with more amr levels than the original run
then some fgmax arrays have to be read in with the old length mxnold
not the new number of levels mxnest.
=> Bug fix for restart with fgmax grids and mxnest increase

src/python/geoclaw/util.py
Computes the bearing from (x0,y0) to (x1,y1) on the sphere, sometimes
useful in conjunction with util.haversine, which computes great circle distance.
In particular this can be used to define a radially symmetric velocity field on the sphere as explained in the docstring.
=> add a function util.bearing

src/2d/shallow/getmaxspeed.f90
The subroutine `geoclaw/src/2d/shallow/getmaxspeed.f90` estimates the maximum wave speed on a patch, looping over all cells.  In dry cells it was doing a lot of arithmetic including sqrt's in order to do no update of the max value.  This routine is now simplified and should be faster on patches with lots of dry cells.
Also I noticed this on a problem where the depth `val(1,i,j)` was slightly negative and it was taking sqrt of a negative value, when it should have setting the wave speed to 0 in that cell.  I'm not sure how a negative value got in here since it should have been set to zero in `b4step`, but that's a different issue.  At any rate the new version won't have this potential problem.
=> improve getmaxspeed.f90 for dry cells

src/2d/shallow/amr2.f90, src/2d/shallow/check.f, src/2d/shallow/restrt.f, src/2d/shallow/topo_module.f90, src/2d/shallow/upbnd.f
goes along with new version in amrclaw https://github.com/clawpack/amrclaw/pull/268  
This greatly reduces the length of the alloc array. RJL was running into excessive storage requirements with 2000 patches on finest level.  Also saved aux_finalized in topo_module to make restarts binary compatible with non-restarted runs.
=> WIP: Lower storage prepc 

src/python/geoclaw/marching_front.py
Most changes are in the docstring, where it incorrectly said that points are
chosen if `Ztopo <= Z2`, for example, when in fact the points are chosen only
if `Ztopo < Z2` when marching.
(Similar updates will be made in clawpack/doc.)
One change in the code: now set `cond0` to initially mark as unchosen those
points for which `Ztopo >= Z2`, rather than `>`, to be consistent with the
the way other points are chosen.
This should actually have no effect on the points eventually chosen, and
at any rate is a corner case that could only give different behavior
if the topo file being processed has some values exactly equal to `Z2`,
but it is best to make it consistent for clarity.
=> Fix <= to < in marching_front.py

src/2d/shallow/filpatch.f90, src/2d/shallow/filval.f90, src/2d/shallow/qinit.f90
This fixes a couple bugs in the `force_dry_init` array capability added in v5.7.0, see http://www.clawpack.org/force_dry.html
Array indexes were calculated improperly in `filval` due to not including ghost cells in the calculation, possibly leading to one or two cells near shore that should have been filled with water but are mistakenly forced to be dry initially.  In some cases this results in a significant wave being generated as water rushes into the dry cells from neighboring wet cells, so the shoreline appears to radiate nonphysical waves.  This showed up in some gauge results in narrow waterways and bays that had highly-oscillatory behavior before the tsunami should have arrived.
There was also some unintended logic with .or. rather than .and. in testing if `(t <= tend_force_dry)`. …
=> Fix force_dry_init indexes and tests

src/2d/shallow/surge/model_storm_module.f90
This PR makes sure that the TC storm vortex rotates counter-clockwise on the northern and clockwise on the southern hemisphere (see #514).
=> Set orientation of TC according to hemisphere

src/2d/shallow/geoclaw_module.f90, src/2d/shallow/surge/model_storm_module.f90
The very long discussion in #521 basically breaks down to this tiny detail: Even though it's never documented in the literature, the Holland 1980 wind field model requires to take the absolute value of the Coriolis parameter on the southern hemisphere. This also seems to apply to the CLE model (this is not mentioned in the CLE reference paper).
To make clear that this only affects the Holland 1980 and CLE models and no other wind field model, I removed the unused references to the Coriolis parameter in all other wind field models.
=> coriolis: use absolute value for all wind field models

src/2d/shallow/surge/model_storm_module.f90
GeoClaw currently does not allow `t0` to be before the available track time.  There is therefore a floating point comparison that checks to see if `t0 < track_t0`.  Before this was implemented with
```fortran
t0 <= storm%track(1, 1) - TRACKING_TOLERANCE
```
which usually works except when `t0` and `storm%track(1, 1)` get large enough (not even really that large).  Instead this PR changes this comparison to
```fortran
t0 - storm%tracK(1, 1) < -TRACKING_TOLERANCE
```
which is safer from a floating point case.
=> Fix Floating Point Bug in Storm Track Time Comparison

src/python/geoclaw/topotools.py
This PR incorporates two minor bug fixes to `Topography.plot()`:
- Use the `axes` provided to the function if need be.  Before for the call to `pcolorcells` this was being ignored and only would work if the `axes` in question was the active one.
- For non longitude-latitude plotting setting the aspect would not work as the code assumed longitude-latitude coordinates.  To fix this I added a new key-word argument that can be set to simply use `axes.set_aspect('equal')`, which more than likely should work at least for something like meters.
=> Fix missing axes and non-long-lat plotting

src/2d/shallow/advanc.f, src/2d/shallow/gauges_module.f90, src/2d/shallow/restrt.f
I changed the `print_gauges_and_reset_nextLoc` function to print all gauge data using the same output file unit number `OUTGAUGEUNIT` rather than creating a unit number based on this base plus the OMP thread number.  And I put this code in an OMP critical block so that only one thread can be doing this at a time.
The other approach allows writing in parallel, in principle, but recently I've been having seg faults when using lots of threads that seems related to this. It also seems potentially bad practice since we don't know what unit numbers will be used for writing gauges, and we use other unit number for other purposes, so there are potentially conflicts.
I don't think this will introduce any bottlenecks.
=> Print gauges in a critical section, using a single unit number

src/python/geoclaw/kmltools.py
This didn't used to throw an error but now it does.
=> savefig transparent param lower case

src/python/geoclaw/kmltools.py
A minor bug fix in addition to setting the colorbar kml figures to not have a transparent background (so the text can be read).
=> Savefig transparent false

src/python/geoclaw/fgout_tools.py
A very trivial correction but typo in fgout_tools.py: `binary63` to `binary64`
=> fix typo in an error message

src/2d/shallow/fgmax_finalize.f90
Filename for fgmax output file should be based on `fg.fgno` since that is specified by the user, rather than just numbering them sequentially.
=> Fix fgmax_finalize.f90 to construct proper filename

src/python/geoclaw/dtopotools.py
=> dtopotools: change 'is' to '==' to avoid a warning

src/python/geoclaw/topotools.py
The arguments were also re-ordered so `topo_type` follows `path`, since this is the most common use case (`topo_func` is now third). So you can do:
topo = topotools.Topography(filename, 3)
to create a `Topography` object and read data from filename with `topo_type=3`.
Before, you had to do
topo = topotools.Topography()
topo.read(filename, 3)
Not a major change but after years of doing this, I'm tired of it.
This is also now consistent with `dtopotools`, where you can do something similar.
=> topotools.Topography.__init__ now calls read() if path given.

src/python/geoclaw/data.py, src/python/geoclaw/fgmax_tools.py
Add parameter `indexing` to FGmaxGrid.read_output, with default `ij` for backward compatibility (but with a bug fixed in computing `x,y` from `X,Y`.
Setting `indexing='xy'` results in fgmax grid arrays that are indexed the same way as topofiles, 
X[j,i],Y[j,i] corresponds to point x[i],y[j]
This is useful if you want to save the fgmax results in the same format as  topofiles, using topotools.Topography.write().
=> Fgmax indexing

src/python/geoclaw/fgout_tools.py
I mis-remembered the name of the standard exception, `InputError` is not defined.
=> change InputError to ValueError

src/2d/shallow/restrt.f
This reverts the reversion from #566 since #564 seems ok after all.
It could be cleaned up further at some point in the future.
=> Repeat fix restart frameno from #564

src/2d/shallow/geoclaw_module.f90, src/2d/shallow/src2.f90, src/python/geoclaw/data.py
So that sphere source terms can be selected in setrun.py by setting
`rundata.geo_data.sphere_source`
Added to data.py, geoclaw_module.f90 and used in src2.f90.
For now set default to 0 for backward compatibility, but default
should eventually be 1 so that source term in mass is included.
=> Add sphere_source parameter

src/python/geoclaw/meson.build
Only installs python files for now.
This is the first phase of switching to meson (away from distutils). This allows meson to install python files only. The second phase is to add compilation of the Fortran extensions (for Python).
For now, this will have no effect since the meson build is not enabled at the top level.
=> Add meson.build.

src/2d/shallow/set_eta_init.f90, src/2d/shallow/topo_module.f90, src/2d/shallow/topo_update.f90
Addresses #539. Also addresses one other issue. Previously, the total number of grid cells in your supplied topography was limited to a 4-byte integer's values (2\**31 -1). This was violated, for example, when using a large chunk of a global 15-arcsecond DEM (which has occasionally been necessary when running a global model to avoid model instability due to boundary fluxes). This PR changes that limit to a 8-byte integer (2\**63 - 1).
=> Include ghost cells when clipping netcdf and handle large topography

src/2d/shallow/tick.f
In some tests this leads to fewer ntogo errors (too many dt reductions) than the old way, but doesn't entirely fix the problem.
This PR also contains some other modifications to tick.f:
- Output frames rather than a checkpoint file if it dies with too many dt reductions (cannot properly checkpoint since not at end of coarse timestep)
- Some debug statements that can be turned on
- Properly compute `timenew`
- Look for file STOP rather than STOP.txt to signal user wants to stop and checkpoint ASAP.
=> compute new ntogo in tick.f rather than incrementing by 1

src/python/geoclaw/meson.build
@ketch found a fix to the module _nonuniform_grid_tools.py_ not being imported with
`from clawpack.geoclaw import nonuniform_grid_tools`.
=> Add nonuniform_grid_tools to meson.build

src/python/geoclaw/kmltools.py, src/python/geoclaw/util.py
`util.gctransect` computes points on a great circle connecting two points specified by lat-long coordinates.  If the points are far apart then this transect is more sensible to use for plotting a cross-section of a tsunami than the straight line in lat-long space connecting the points.
`kmltools.transect2kml` creates a kml file to view the points on Google Earth.
Also fixes a bug in `util.bearing` that computes the bearing from one point to another.
=> Add gctransect function to util.py

src/2d/shallow/set_eta_init.f90
Fix a bug introduced when converting from int*4 to int*8.
=> Fix ij index into dtopowork in set_eta_init

src/1d_classic/shallow/claw1ez.f, src/1d_classic/shallow/setaux.f90, src/2d/shallow/qinit.f90, src/2d/shallow/stepgrid.f
Mostly transparent updates for shallow that make some subroutines work fine also for bouss version so we don't replicate code.
Also change `fgout_interp_needed` array from allocatable to stack based.
=> Updates for bouss in src/2d/shallow

src/python/geoclaw/marching_front.py
Fix test since `where` returns empty numpy array not empty list if nothing matches.
=> fix test in marching_front.py

src/python/geoclaw/data.py
Starting in v5.9.1, spherical source terms originally missing from the shallow water equations could be added as an option. Change so that the default behavior is to add the source term in mass but not the terms in the momentum equations, which seem to have almost no effect on practical problems.
This will change the results for some tsunami propagation problems over long distances, particularly in the N-S direction, but should give more correct behavior.
See https://www.clawpack.org/sphere_source.html and also #569, #570.
=> set rundata.geo_data.sphere_source = 1 by default in data.py

examples/bouss/radial_flat/1d_radial/Makefile
Flat topo specified in `flat.tt1`.
Ignore incorrect commit message.
=> Clean up Makefile for examples/bouss/radial_flat/1d_radial

src/2d/shallow/topo_module.f90
Since we still use topotype 1 for simple flat topography.
=> Remove deprecation warning for topotype 1

src/2d/shallow/multilayer/setaux.f90
Update src/2d/shallow/multilayer/setaux.f90 to elimate arguments from cellgridintegrate calls.
The same change was made in shallow/setaux.f90 in #579 but missed here.
=> remove topo module args from call to cellgridintegrate in multilayer

examples/bouss/radial_flat/Makefile, examples/bouss/setenv.sh
To make sure user has necessary environment variables set to use PETSc, MPI. Otherwise gives an error, e.g. `Makefile:36: *** PETSC_DIR not set.  Stop.`
Also a new target, so that `make check` prints out the relevant variables, e.g.
```
===================
CLAW = /Users/rjl/clawpack_src/clawpack_master
OMP_NUM_THREADS = 6
BOUSS_MPI_PROCS = 6
PETSC_OPTIONS=-options_file /Users/rjl/clawpack_src/clawpack_master/geoclaw/examples/bouss/petscMPIoptions
PETSC_DIR = /Users/rjl/git/Clones/petsc
PETSC_ARCH = arch-darwin-c-opt
RUNEXE = /Users/rjl/git/Clones/petsc/arch-darwin-c-opt/bin/mpiexec -n 6
FFLAGS = -O2 -fopenmp -DHAVE_PETSC -ffree-line-length-none
===================
```
We might want to adopt something similar in `Makefile.common` to be used in all Clawpack examples (showing only CLAW, …
=> Better comments and new tests in examples/bouss/radial_flat/Makefile

src/python/geoclaw/topotools.py
Previous value `-9999` did not have enough digits since new etopo 2022 data has this as an actual topography value in the Mariana Trench (when written with `Z_format='%.0f'`).
=> change nodata_value to -99999 in topotools.py

src/2d/shallow/gauges_module.f90
This fixes a bug caused by code that was meant to divide the pressure at a gauge by the ambient pressure.  Unfortunately this really never worked and somewhat randomly was dividing other gauge values by the ambient pressure.  This fix removes the division and leaves it up to post-processing to do this if one wants that and therefore fixes the bug.
=> Fix bug related to tracking pressure at gauges

examples/tsunami/chile2010_fgmax-fgout/Makefile, examples/tsunami/chile2010_fgmax-fgout/README.rst, examples/tsunami/chile2010_fgmax-fgout/make_fgout_animation.py, examples/tsunami/chile2010_fgmax-fgout/make_fgout_animation_with_transect.py, examples/tsunami/chile2010_fgmax-fgout/setplot_fgout.py
This script has been simplified since I realized that `update_artists` are defined globally and do not need to be passed into `update`, unpacked, and repacked.  Moreover if `blit==False` this tuple is not needed at all.  This does not seem to slow it down at all.  Getting rid of `update_artists` makes it easier to adapt to other animations where many things need to be updated in each frame.
I also cleaned up several other things in the script and added a better doc string.
=> Improve chile2010_fgmax-fgout example script for fgout animation

src/python/geoclaw/dtopotools.py
The default is now `'%.3f'` (millimeter resolution), making smaller dtopo files than previously. One could probably get away with `'%.2f'` in general.  This becomes important for PTHA studies involving a large number of time-dependent deformations.
=> Add dZ_format parameter to DTopography.write function

src/2d/shallow/surge/model_storm_module.f90
This addresses an issue in the edge case where `r`, the distance of the grid cell centroid to the storm eye, is 0. Previously this would result in either floating point errors or nan's in the `q` array, depending on the compile flags.
[Google group discussion](https://groups.google.com/g/claw-users/c/BPAfEZZTrMI/m/8oE1idBdBgAJ)
=> handle 0 radius

src/2d/shallow/gauges_module.f90
This addresses https://github.com/clawpack/geoclaw/issues/541, creating filenames in the same format as previously if the gauge number has 5 or fewer digits, e.g. `gauge00012.txt`, but allows up to 15 digits, e.g. `gauge123456789.txt`.
If this seems ok, I'll do the same thing in amrclaw.
Note that gauges are still read in fine for plotting regardless of the number of digits, with no changes needed in `pyclaw.gauges.GaugeSolution`.
Note that this is implemented via these two lines (where `numstr` is a character variable):
```
write (numstr,'(I0.5)') num
gauges(i)%file_name = 'gauge'//trim(numstr)//'.txt'
```
This is a much cleaner way to do it than the old way of starting with `gaugexxxxx.txt` and changing one character at a time!
We should eventually make this change also in creating …
=> Gauge filenames

examples/storm-surge/ike/setplot.py, examples/storm-surge/isaac/setplot.py, examples/storm-surge/isaac/setrun.py, src/python/geoclaw/surge/plot.py, src/python/geoclaw/util.py
This PR finally fixes an errant line that showed up sometimes.  This ended up a result of the gauge plots always plotting data unless a plot type `1d_empty` is used.  Instead this uses `time_scale` to convert from seconds to days so it should match better with other plots.  The Isaac example also now includes an example of how to fetch and plot observed data.
=> Fix up gauge plotting for storm surge

src/2d/shallow/fgout_module.f90, src/python/geoclaw/fgout_tools.py
Allow specifying `fgout.output_times` as a general list or array of times rather than equally spaced, if you set `fgout.output_style = 2`.  The default is `fgout.output_style = 1` that takes the previous input. Changes to `fgout_tools.py` allow specifying these values in `setrun.py`.
Then we also made this more general so that it could handle D-Claw output as well as GeoClaw, with a new attribute `fgout.dclaw` that is `False` by default, but setting this to `True` outputs 7 components of `q` instead of only 3 (plus `eta` in both cases).
I plan to also modify this so that you can specify fewer components rather than all of them. 
Also cleaned up a bunch of trailing white space.
=> improvements to fgout_module for t arrays and D-Claw

src/python/geoclaw/fgout_tools.py
Now that `output_style==2` is supported for fgout grids (an array of times, see https://github.com/clawpack/geoclaw/pull/617), the function fgout_tools.FGoutGrid.read_fgout_grids_data needs to be fixed to properly read in the new format of `fgout_grids.data`.  And also note that `nout` now comes before `tstart` and `tend` for `output_style==1`.
I was thinking we might might want to rewrite this code so that it makes a `.data` file with `:=` in the lines, similar to `claw.data` and others, so that `clawutil.data.ClawData.read` can be used to read it rather than depending on a particular line ordering.  But the problem is that there might be more than one fgout grid specified in the file, so I don't think this will work. (Similarly for fgmax).
=> fix fgout_tools.FGoutGrid.read_fgout_grids_data for time array

src/python/geoclaw/surge/plot.py, src/python/geoclaw/surge/storm.py, src/python/geoclaw/topotools.py
Add a `plot` function to the `Storm` object that can
1. plot the track and time points of the storm,
2. plot a swath of the storm that is a given radius from the track,
3. and plot the category of the storm.
All of these have some options about how it determines what and how to plot.  There are also some examples that have now been added to [surge examples](https://github.com/mandli/surge-examples/tree/master/synthetic/boundary), especially as a means for looking at boundary conditions.
=> Add Plotting Capabilities to Storm Object

examples/bouss/README.txt, examples/bouss/radial_flat/README.rst, src/2d/bouss/amr2.f90
This was modified in the shallow/amr2.f90 code to support more fgout flexibility in #624, and this change is also required in the bouss version.
Also enhanced the examples/bouss README files a bit.
=> Fix src/bouss/amr2.f90 call to set_fgout, adding nvar

examples/tsunami/chile2010_fgmax-fgout/plot_fgout.py, src/python/geoclaw/fgout_tools.py
Should be `[h,hu,hv,eta]` as in old versions, but now `qmap['eta']` varies depending on equations being solved (e.g. `geoclaw-bouss` or `dclaw`).
=> Properly set fgout q_out_vars to default

src/2d/shallow/surge/storm_module.f90, src/python/geoclaw/surge/plot.py, src/python/geoclaw/surge/storm.py
This PR adds a new way to display time in the figure titles that is more standardized.  Defaults to the old way for now.
Also includes plotting fixes to the `Storm` object's `plot` function.
=> Change Time Format of Storm Surge Title

src/python/geoclaw/surge/plot.py, src/python/geoclaw/surge/storm.py, src/python/geoclaw/topotools.py, src/python/geoclaw/util.py
Adds better (easier) track plotting along with:
- Better time titles for surge
- Better storm plotting
- Better error handling for NetCDF topo files
- Minor bug fix in doc-string
=> Add storm track plotting

src/2d/shallow/gauges_module.f90
Previously if `min_time_increment > 0` was set for a gauge it wouldn't capture the gauge value until this long after the starting time value `t1` specified for the gauge.
=> modify so gauge values always written at start time regardless of min_time_increment

examples/bouss/README.txt, examples/bouss/petscMPIoptions, examples/bouss/radial_flat/Makefile, examples/bouss/setenv.sh
Fixed radial_flat/Makefile, setenv.sh, and petscMPIoptions for the latest version, and improved the README.
=> Updates to bouss files for PETSc setup

src/2d/shallow/b4step2.f90, src/2d/shallow/geoclaw_module.f90, src/2d/shallow/getmaxspeed.f90, src/2d/shallow/src2.f90, src/python/geoclaw/data.py
A new parameter `rundata.geo_data.speed_limit` can be set in `setrun.py` and is used in `b4step2.f90` and `getmaxspeed.f90` to scale down the fluid speed `sqrt(u**2 + v**2)` if it is larger than this value (preserving the flow direction).
This helps avoid crashing the code with "too many dt reductions" in cases when flow off very steep topography with delta B larger than the fluid depth gives big speeds in the Riemann solution (shallow water equations aren't valid for flow off a cliff).
If not specified in `setrun.py`, the default value `speed_limit = 50` m/s (approx 100 knots) is set in `data.py`. This is much larger than physically reasonable speeds for most problems, so this should give consistent results with past version of GeoClaw for runs that don't die along the way.
In practice …
=> New speed_limit parameter to avoid too many dt reductions

src/python/geoclaw/surge/storm.py
@mandli: I'm trying to run all the GeoClaw examples and  I don't know what's wrong with this.
I fixed nested double quotes and then it didn't like an f-string split between lines, but now it still gives an error...
```
$ cd $CLAW/geoclaw/examples/storm-surge/ike
$ make data
Traceback (most recent call last):
File "/Users/rjl/git/clawpack/geoclaw/src/python/geoclaw/surge/storm.py", line 1070, in write_geoclaw
f"{np.datetime_as_string(self.time_offset,unit='s')}\n\n")
TypeError: input must have type NumPy datetime
```
=> Trying to fix storm.py

src/2d/shallow/valout.f90
Add a missing comma that didn't seem to cause a problem with earlier gfortran but throws an error with 15.1.0
=> fix timing_line definition in valout.f90

src/python/geoclaw/kmltools.py
`kmltools.py` can be used to plot flagregions, extents of topo/dtopo files, gauge locations, transects, etc. on Google Earth, but doesn't always work well unless the longitude(s) are entirely in the range -180 <= x <= 180, which can be impossible if the computational domains crosses the dateline in the Pacific.  I was reminded of this recently when modeling the Kamchatka event with a domain having 140 <= x <= 210, in which case a flagregion around Maui might have longitude limits 203 <= x <= 204.  With the original kmltools this region displays ok, but clicking on it does not pop up the expected text box giving the flagregion parameters.  With the new version, these x values would be replaced by -157 <= x <= -156 in the location of the box, while still giving the original  setrun values …
=> Improve kmltools for regions / lines crossing the dateline
