clawpack/geoclaw

- src/2d/shallow/src1d.f90
- src/2d/shallow/src2.f90
Tests did not catch this but there were a couple uninitialized variables in the wind-forcing function.  Also cleaned up some extra parameters that were no longer used.
> Add missing storm location and direction

- src/2d/shallow/advanc.f
Fixes PR #140 to be in line with clawpack/amrclaw#129.
> fix call to print_gauges in advanc 

- src/2d/shallow/tick.f
> change order of operations in tick.f so restart generates exactly same grids

- src/python/geoclaw/dtopotools.py
- tests/old_topotools.py
standard_units was being overwritten and output format for writing subdivided fault fixed
> dtopotools.py fixes

- src/python/geoclaw/topotools.py
Fixed a couple places that were missed in 377b7041ad
> fix delta to tuple in topotools write and plot functions

- src/2d/shallow/surge/storm_module.f90
- src/python/geoclaw/data.py
Allows setting empty arrays or None values for wind_refine and R_refine
parameters that control storm based refinement.  Also adds ability to
set the wind_index and pressure_index so that custom layout of the aux
array is allowed.
> Add surge indexing options and modify surge refinement settings

- examples/multi-layer/plane_wave/Makefile
- tests/multilayer/Makefile
This updates to the new version of the Makefiles
> Update multilayer example Makefile

- src/2d/shallow/Makefile.geoclaw
Minor correction for source type.
> Correct file suffixes in default Makefile source list

- src/2d/shallow/utility_module.f90
print message and quit if too many values on line for parse_values function
> add error test to parse_values function

- src/python/geoclaw/kmltools.py
Added an option to create separate kml files for the Domain and each region,  for ease in viewing on GoogleEarth -- each can be turned on or off separately.
Also added functions to make kml files for each topo or dtopo file to show their extent.
> kmltools updates

- src/2d/shallow/Makefile.geoclaw
- src/2d/shallow/amr2.f90
- src/2d/shallow/tick.f
- src/2d/shallow/topo_module.f90
- src/2d/shallow/utility_module.f90
- src/python/geoclaw/dtopotools.py
- src/python/geoclaw/fgmax_tools.py
- src/python/geoclaw/kmltools.py
- src/python/geoclaw/topotools.py
I had to merge #208 by hand because of a mysterious merge conflict in tick.f.
This PR now replaces #208.
> Batch gauge output

- examples/multi-layer/plane_wave/Makefile
- examples/storm-surge/ike/setplot.py
- examples/storm-surge/ike/setrun.py
- src/2d/shallow/amr2.f90
- src/2d/shallow/gauges_module.f90
- src/2d/shallow/surge/storm_module.f90
- src/2d/shallow/tick.f
- src/python/geoclaw/data.py
- tests/multilayer/Makefile
- tests/storm_surge/setrun.py
Includes
- Missing call to surge module initialization from the new gauge capabilities
- Cleans up some of the gauge output
- Fixes the multilayer makefiles
- Adds back the ability to output the time step info relative to landfall in days
> Fixes a number of minor bugs

- src/python/geoclaw/kmltools.py
added line2kml, poly2kml and improved several other tools
> Enhanced kmltools

- examples/multi-layer/plane_wave/Makefile
- examples/multi-layer/plane_wave/setrun.py
- examples/storm-surge/ike/setrun.py
- examples/tsunami/bowl-radial/setrun.py
- examples/tsunami/bowl-slosh/setrun.py
- examples/tsunami/chile2010/Makefile
- examples/tsunami/chile2010/setrun.py
> remove RESTART from Makefile and comment from setrun.py

- examples/multi-layer/plane_wave/setplot.py
- examples/storm-surge/ike/setplot.py
- examples/tsunami/bowl-radial/setplot.py
- examples/tsunami/bowl-slosh/setplot.py
- examples/tsunami/chile2010/setplot.py
Same changes as in clawpack/amrclaw#182.
> make plotdata an optional argument in setplot

- src/2d/shallow/gauges_module.f90
Corrects problem found in clawpack/amrclaw#180.
> Expand gauge header field

- src/2d/shallow/setaux.f90
Addresses clawpack/doc#154 so that Sphinx properly syntax colors the file.
> Remove format lines with line number references

- src/python/geoclaw/util.py
Better notation and more flexible. Should be backward compatible.
> Improve util.haversine

- src/python/geoclaw/dtopotools.py
Add additional `coordinate_specification` for dtopofiles with (long,lat) specified updip and upstrike.
> Upstrike corner

- examples/multi-layer/plane_wave/qinit.f90
- examples/multi-layer/plane_wave/qinit_module.f90
- examples/multi-layer/plane_wave/setrun.py
- examples/storm-surge/ike/setrun.py
- src/2d/shallow/geoclaw_module.f90
- src/2d/shallow/multilayer/b4step2.f90
- src/2d/shallow/multilayer/gauges_module.f90
- src/2d/shallow/multilayer/getmaxspeed.f90
- src/2d/shallow/multilayer/multilayer_module.f90
- src/2d/shallow/multilayer/setaux.f90
- src/2d/shallow/multilayer/src1d.f90
- src/2d/shallow/multilayer/src2.f90
- src/2d/shallow/multilayer/stepgrid.f
- src/2d/shallow/multilayer/valout.f
- src/2d/shallow/setaux.f90
- src/2d/shallow/src1d.f90
- src/2d/shallow/src2.f90
- src/2d/shallow/surge/constant_storm_module.f90
- src/2d/shallow/surge/holland_storm_module.f90
- src/2d/shallow/surge/storm_module.f90
- src/python/geoclaw/data.py
- tests/multilayer/qinit.f90
- tests/multilayer/qinit_module.f90
- tests/multilayer/setrun.py
- tests/storm_surge/setrun.py
In order to preserve well-balancing properties for strong pressure gradients the contribution from the contribution is now incorporated into the Riemann solver itself.  The PR in the Riemann repository is clawpack/riemann#116.
> Move Pressure Gradient Calculation to Riemann Solver

- src/2d/shallow/filval.f90
variable was not initialized when varRefTime set to False
> minor bug when not using varRefTime

- src/python/geoclaw/dtopotools.py
Default is 0, set to -360. for change from E to W longitude.
Consistent with parameter in etopotools.py
> Allow specifying longitude_shift in SiftFault.

- test.txt
> Revert "Test Shot"

- examples/storm-surge/ike/setplot.py
- examples/storm-surge/ike/setrun.py
- src/2d/shallow/surge/holland_storm_module.f90
- src/2d/shallow/surge/storm_module.f90
- src/2d/shallow/valout.f
- src/python/geoclaw/surge/plot.py
Refactor of storm surge plotting code
Includes fixing a number of bugs that have cropped up including
- Plotting the storm track
- Landfall time offsets
Also includes a significant decrease in code and removal of
matplotlib 2.x deprecated features.
> Fix surge plotting

- examples/multi-layer/plane_wave/setplot.py
- examples/multi-layer/plane_wave/setrun.py
- src/2d/shallow/multilayer/valout.f
- src/python/geoclaw/multilayer/plot.py
Refactor and fix multilayer plotting.
> Basic refactor of multilayer plotting

- src/2d/shallow/upbnd.f
can't reproduce the bug, but added debugging info in case it happens again
> added debugging info to upbnd

- src/python/geoclaw/topotools.py
in topotools.Topography.delta, set self._delta = (dx,dy) in case dy != dx
> fix topotools.Topography.delta to include dy

- src/python/geoclaw/topotools.py
aspect ratio wasn't being properly set because of location of `set_aspect` command.
> set aspect ratio at end of Topography.plot

- src/2d/shallow/Makefile.geoclaw
- src/2d/shallow/check.f
- src/2d/shallow/gauges_module.f90
- src/2d/shallow/multilayer/gauges_module.f90
- src/2d/shallow/restrt.f
allow maxgr to become larger and create new larger arrays (rnode, node,etc).
also changed gauges_module.
use with amrclaw branch with same name.
> Flex max grids

- src/python/geoclaw/dtopotools.py
- tests/test_dtopotools.py
Added python implementation of surface deformation model due to Comninou and Dundurs, causally referred to as the "triangular version of the Okada model". This allows the computation of surface dislocation due to the slip of a subfault that has triangular shape.
> Adding surface deformation model for triangular sub-faults

- src/2d/shallow/Makefile.geoclaw
- src/2d/shallow/flag2refine2.f90
- src/2d/shallow/multilayer/flag2refine2.f90
Updating flag2refine2 to work with new UNSET flag in the amrflags array.
> Add UNSET option to flag2refine2

- .travis.yml
to see if travis then works on clawpack/clawpack
> add liblapack-pic to apt-get

- src/2d/shallow/valout.f90
eta was printing out as all zeros
> valout.f90 missing line

- src/2d/shallow/amr2.f90
- src/2d/shallow/valout.f90
This mostly brings the GeoClaw refactor into alignment with everything that happened in the AMRClaw refactor.
> Minor Corrections to `valout` Refactor

- src/python/geoclaw/surge/storm.py
fixing xarray version issue in read_ibtracs function. addresses #332
> use np.where instead of xr.where to fix xarray version issue

- examples/multi-layer/bowl-radial/setrun.py
in examples/multi-layer/bowl-radial
> set data.layer_index = 1

- .travis.yml
- src/python/geoclaw/dtopotools.py
very minor so I'll merge it in.
> fix typo in SubFault.dynamic_slip

- src/2d/shallow/surge/storm_module.f90
Summary
------
The implementation of the Powell drag law was previously incorrect as the plots below show. This change rewrites the `powell_wind_drag` function based on the implementation in ADCIRC.
Testing
-------
Manually tested by running Katrina model.
Output of `nosetests`:
```
geoclaw (powell)$ FFLAGS=-llapack nosetests
...........S...S/home/nav/claw/clawpack/clawpack/geoclaw/surge/storm.py:451: UserWarning: *** Cannot yet automatically determine the
maximum wind radius.  Will write out GeoClaw
formats but note that these will not work
when running GeoClaw currently without a custom
`max_wind_radius_fill` function passed as argument
to the `write` function.
warnings.warn(missing_data_warning_str)
/home/nav/claw/clawpack/clawpack/geoclaw/surge/storm.py:643: UserWarning: *** Cannot …
```
> Fix Powell drag law

- src/python/geoclaw/surge/storm.py
Same as https://github.com/clawpack/doc/pull/202 ;-)
> Hyperlink DOI to preferred resolver

- src/2d/shallow/setaux.f90
Also includes some efficiency changes and clarifications regarding the role of the routine.  This includes:
- Rewriting the description of the function and adding some notes.
- Removing extraneous if-statement checks from the interior of loops.  This mostly involves separating out loops that were redundantly checking whether it should set some of the aux fields from within loops.
- Remove the `forall` statements as they are problematic for debugging and today do not generally lead to speedups.
- Remove some outdated code.
> Fix periodic BCs problem with topography

- examples/tsunami/chile2010/maketopo.py
The redirect from www.geoclaw.org to UW website was failing.
> fix url in chile2010/maketopo.py

- .gitignore
Adds `__pycache__`, `*.log`, and `.ipynb_checkpoints` to `.gitignore`
> add log, __pycache__, and ipynb_checkpoints to .gitignore

- src/python/geoclaw/surge/quality.py
See docstring for info on how the function works. This will definitely be useful for the Climate Impact Lab work, so if you don't think this is a good general function, we're happy to just keep it on our fork. Otherwise, feel free to merge! I'm imagining other potential ways to do QA/QC that could be added to this module in the future. Also happy to rearrange the structure/move to another module if you think there's a better way to structure it.
> add QA/QC module and instability checker function

- src/2d/shallow/setaux.f90
Trying #379 again, with a new text editor so that whole file doesn't look new
> move friction to after bathy is set

- src/python/geoclaw/surge/quality.py
- adding a check to the `quality` module that finds the maximum normal fluxes and currents at the boundary in the last output frame(s) of a model
Useful for evaluating instability as large boundary fluxes are indicative of instability. This can be run during a model if needed to check if its blowing up
> add boundary flux test

- tests/chile2010_adjoint/regression_tests.py
Modify tests/chile2010_adjoint/regression_tests.py to copy adjoint subdirectory and run that code as part of setUp.
Contains some debug print statements too.
> WIP: Test travis adjoint

- .gitignore
- examples/storm-surge/synthetic/.gitignore
- examples/storm-surge/synthetic/Makefile
- examples/storm-surge/synthetic/README.rst
- examples/storm-surge/synthetic/setplot.py
- examples/storm-surge/synthetic/setrun.py
- src/2d/shallow/multilayer/setaux.f90
- src/2d/shallow/multilayer/src2.f90
- src/2d/shallow/setaux.f90
- src/2d/shallow/surge/model_storm_module.f90
- src/python/geoclaw/units.py
The `setaux` routine for multilayer flow had some issues with some newer changes to the routine.
> Fix multilayer setaux

- examples/tsunami/bowl-slosh-netcdf/README.rst
- tests/netcdf_topo/README.txt
Add a couple README files for users to help figure out what they need to install to run the new example or the test.
> netCDF README files

- src/2d/shallow/surge/storm_module.f90
Should be Chavas, Lin, and Emanuel, not Emmanuel :)
https://journals.ametsoc.org/doi/full/10.1175/JAS-D-15-0014.1
> Typo in CLE attribution

- src/2d/shallow/multilayer/multilayer_module.f90
Addresses Issue #421 
Compiling with debug flags suggests these exponents had been coerced to 1
> Bug fix integer-->float division in vel_diff_eigen

- src/python/geoclaw/topotools.py
`Topography.set_xyZ`: New convenience function that allows setting `x,y,Z` components of a Topography object.  
`Topography.write` had an unused parameter `masked`.  Now replaced with `fill_value` as a value to write out for masked grid points, if `topo.Z` is a masked array.
`plot` function improved by using `plottools.pcolorcells` rather than `pcolor` or `imshow` (Requires https://github.com/clawpack/visclaw/pull/257)
This plots all data values on cells centered at `topo.x` and `topo.y` values, rather than leaving out a row and column and being offset.
See http://www.clawpack.org/new_features_for_v5.7.0/notebooks_html/pcolorcells.html
`read_netcdf` improved to return numpy arrays, and to check for overlapping indices more efficiently.
> misc topotools improvements

- src/python/geoclaw/dtopotools.py
Because I did it incorrectly in #427.
> again fix find to where in dtopotools

- examples/run_tests.py
- examples/tsunami/chile2010/README.rst
- examples/tsunami/chile2010/setplot_kml.py
- examples/tsunami/eta_init_force_dry/Makefile
- examples/tsunami/eta_init_force_dry/README.rst
- examples/tsunami/island-particles/setplot.py
- examples/tsunami/radial-ocean-island-fgmax/README.rst
- src/python/geoclaw/multilayer/plot.py
Fixed a number of minor issues in various examples.
`multi-layer/plane_wave` is still broken due to https://github.com/clawpack/clawutil/issues/146
> Fix examples for v5.7.0

- examples/tsunami/chile2010_adjoint/adjoint/README.rst
- examples/tsunami/radial-ocean-island-fgmax/Makefile
- examples/tsunami/radial-ocean-island-fgmax/maketopo.py
- examples/tsunami/radial-ocean-island-fgmax/setplot.py
- examples/tsunami/radial-ocean-island-fgmax/setrun.py
A couple more fixes to examples for v5.7.0.
> Fix examples

- examples/multi-layer/plane_wave/setrun.py
- src/python/geoclaw/data.py
This addresses clawpack/clawutil/issues/146
> Fix multilayer data default value

- src/python/geoclaw/surge/storm.py
> Add error handling for atcf files with fewer than 10 columns

- src/python/geoclaw/surge/storm.py
Cleanup code to plot track and intensity of a storm.  Will use `basemap` still if available but will try cartopy first (although not yet implemented).  Also now contains a default basic option if nothing is available.
> Fix up storm.plot so it does something

- src/2d/shallow/setgrd.f
- src/2d/shallow/tick.f
same updates as in https://github.com/clawpack/amrclaw/pull/263.
> fix verbosity_regrid and improve format

- src/python/geoclaw/fgmax_tools.py
Tiny fix, that removed a `ResourceWarning: unclosed file` for me.
> fgmax_tools: close file pointer after reading

- examples/tsunami/radial-ocean-island-fgmax/README.rst
- examples/tsunami/radial-ocean-island-fgmax/make_input_files.ipynb
- examples/tsunami/radial-ocean-island-fgmax/make_input_files.py
- examples/tsunami/radial-ocean-island-fgmax/process_fgmax.ipynb
- examples/tsunami/radial-ocean-island-fgmax/process_fgmax.py
clean up some old imports, add hide-py tags, fix README.
> update notebooks in examples/tsunami/radial-ocean-island-fgmax

- src/2d/shallow/amr2.f90
goes with clawpack/amrclaw#267.  Won't pass tests until that is merged and clawpack/clawpack updated.
> allow memsize to be set in setrun.py

- src/python/geoclaw/kmltools.py
Shows onshore and offshore topography as separate layers.
Currently not very flexible but is useful in quickly creating kmz files
to open on Google Earth showing the onshore topography and offshore
bathymetry as two separate layers.  Constant colors on rectangular grid
cells should be properly rendered to ease exploration of DEMs.
> Add kmltools.topo2kmz function to create kmz file showing topography

- src/python/geoclaw/topotools.py
Adds reading **only** of GeoTIFF files to the topotools `Topography` class.  This should allow someone to then convert a GeoTIFF topography file into another file supported directly by GeoClaw.
> Add geotiff to read for topotools

- examples/tsunami/chile2010_fgmax-fgout/Makefile
- examples/tsunami/chile2010_fgmax-fgout/README.rst
- examples/tsunami/chile2010_fgmax-fgout/make_fgout_animation.py
- examples/tsunami/chile2010_fgmax-fgout/setplot_fgout.py
so its easier to make gallery files.  
`make fgout_plots` now makes the animations and moves them to `_plots_fgout`.
> fix the chile2010_fgmax-fgout example

- src/python/geoclaw/surge/plot.py
> Add add_track function to plot.py

- src/python/geoclaw/data.py
- src/python/geoclaw/fgmax_tools.py
- tests/test_data.py
Addresses #553 by adding a `read` function to the `FGmaxData` object.  Also modifies `fgmax_tools` to avoid a circular import problem.
> Add FGmaxData read function

- examples/multi-layer/bowl-radial/Makefile
- examples/tsunami/bowl-radial/Makefile
- examples/tsunami/bowl-slosh-netcdf/Makefile
- examples/tsunami/bowl-slosh/Makefile
- examples/tsunami/chile2010/Makefile
- examples/tsunami/chile2010_adjoint/Makefile
- examples/tsunami/chile2010_adjoint/adjoint/Makefile
- examples/tsunami/chile2010_fgmax-fgout/Makefile
- examples/tsunami/eta_init_force_dry/Makefile
- examples/tsunami/island-particles/Makefile
- examples/tsunami/radial-ocean-island-fgmax/Makefile
Similar to #538 and as discussed in https://github.com/clawpack/clawutil/pull/156  
Just replacing and no breaking change.
> use CLAW_PYTHON instead of `python` in Makefile

- src/2d/shallow/src2.f90
For shallow water on the sphere there are additional source terms that should have been included but have always been missing from GeoClaw. These are now added to `src/2d/shallow/src2.f90` but are turned off for now for backward compatibility.
The plan is to turn on the source term in mass by default in v5.10.0, and in the meantime do more testing and write up a document describing this change and giving some examples of the impact it has for global scale modeling. (The source terms in the momentum equations so far seem to make very little difference and can be dropped for efficiency, but this should be further investigated.)
To test this currently, change the local variable `sphere_source` and recompile. The plan for v5.10.0 is to add this variable to `geoclaw_module.f90` and allow it to …
> Add source terms on sphere that have always been missing, turned off for now

- src/python/geoclaw/meson.build
Updated the build file to properly install python source in subdirectories.
> Complete meson build.

- examples/tsunami/bowl-radial/setrun.py
- examples/tsunami/chile2010/setrun.py
- src/2d/shallow/tick.f
checkpt style 4 outputs as same times as plotting output
STOP feature creates checkpoint and stops if STOP.txt file found in working directory
Goes with clawpack/amrclaw#288
> Hackathon changes

- src/1d_classic/bouss/claw1ez.f
- src/1d_classic/shallow/b4step1.f90
- src/1d_classic/shallow/claw1ez.f
Fix a typo (line too long) and compute mass in radial case.
> Geoclaw1d fixes

- examples/run_tests.py
- examples/tsunami/eta_init_force_dry/README.rst
- examples/tsunami/eta_init_force_dry/setrun.py
- src/1d_classic/bouss/bouss_module.f90
update gallery links in README and add comment to setrun
> update examples/tsunami/eta_init_force_dry 

- examples/storm-surge/ike/setrun.py
- examples/storm-surge/isaac/setrun.py
> download gulf_carribean.tt3 from geoclaw.org

- examples/bouss/README.txt
- examples/bouss/petscMPIoptions
- examples/bouss/radial_flat/Makefile
- src/2d/bouss/Makefile.bouss
- src/2d/bouss/bouss_module.f90
- src/2d/bouss/buildSparseMatrixSGNcoo.f90
- src/2d/bouss/buildSparseMatrixSGNcrs.f90
- src/2d/bouss/flagregions2.f90
- src/2d/bouss/implicit_update_bouss_2Calls.f90
- src/2d/bouss/petsc_driver.f90
- src/2d/bouss/prepBuildSparseMatrixSGNcrs.f90
- src/2d/bouss/setMatrixIndex.f90
- src/2d/bouss/simpleBound.f90
- src/2d/bouss/testSoln.f90
while implementing periodic bcs found bugs in wall bcs. Also fixed big bug in reentrant corrner. Also using new version of petsc with different options and modified Makefile in radial_flat. Also tested with examples from implicit paper.
> Bouss periodic and matrix reentrant corner and wall fixes

- src/2d/bouss/valout.f90
- src/2d/shallow/multilayer/valout.f90
Continuation of #651 to additional versions of valout.f90
> fix timing_line in bouss and multilayer
